
all:
	gcc -DDEBUG_TRACE -g data.c dictionary.c environment_frame.c evaluator.c hash.c parser.c primitive_function.c primitives.c repl.c special_forms.c tokenizer.c utils.c vector.c environment_vector.c logging.c logging_handler.c serial_handler.c -lreadline -o zombielisp
